export const GET_CONTAINER_BY_ID = "GET_CONTAINER_BY_ID";
export const SET_CURRENT_CONTAINER = "SET_CURRENT_CONTAINER";
export const RESET_CONTAINER = "RESET_CONTAINER";
export const SET_LOADING = "SET_LOADING";